name = "stm32l0xx_hal"
description = "HAL library for STMicroelectronics' STM32L0 MCU series"
version = "0.0.0-dev"

authors = ["Emanuele Zarfati"]
maintainers = ["Emanuele Zarfati <zarfati.tecno@gmail.com>"]
maintainers-logins = ["ezetec"]

[[depends-on]]
gnat_arm_elf = "^13.2.1"
stm32l0xx_cmsis = "*"

[[pins]]
stm32l0xx_cmsis = { url='https://gitlab.com/ezetec-alire-crates/stm32l0xx-cmsis.git', branch='feature/Add-support-for-stm32l011d4' }

[build-switches]
"*".Ada_Version = "Ada2022"
