name = "stm32l0xx_hal"
description = "HAL library for STMicroelectronics' STM32L0 MCU series"
version = "0.5.3-dev"

authors = ["Emanuele Zarfati"]
maintainers = ["Emanuele Zarfati <zarfati.tecno@gmail.com>"]
maintainers-logins = ["ezetec"]

[[depends-on]]
gnat_arm_elf = "^13.2.1"
stm32l0xx_cmsis = "1.0.0"

[[pins]]

[pins.stm32l0xx_cmsis]
url = 'https://gitlab.com/ezetec-alire-crates/stm32l0xx-cmsis.git'
commit = "57b9f1a175607e6d06390001e8f23eed6e5e96a3"

[build-profiles]
"stm32l0xx_cmsis" = "release"

[build-switches]
"*".ada_version = ["-gnatX0"]

[build-switches.release]
optimization    = "size"       # "-Os", "-gnatn", "-ffunction-sections", "-fdata-sections"
debug_info      = "no"         #
runtime_checks  = "none"       # "-gnatp"
compile_checks  = "none"       #
contracts       = "no"         #
style_checks    = "yes"        # "-gnaty3", "-gnatya", "-gnatyA", "-gnatyB", "-gnatyb", "-gnatyc", "-gnaty-d", "-gnatye", "-gnatyf", "-gnatyh", "-gnatyi", "-gnatyI", "-gnatyk", "-gnatyl", "-gnatym", "-gnatyn", "-gnatyO", "-gnatyp", "-gnatyr", "-gnatyS", "-gnatyt", "-gnatyu", "-gnatyx"

[build-switches.validation]
optimization    = "size"       # "-Os", "-gnatn", "-ffunction-sections", "-fdata-sections"
debug_info      = "no"         #
runtime_checks  = "everything" # "-gnato"
compile_checks  = "errors"     # "-gnatwa", "-gnatw.X", "-gnatVa", "-gnatwe"
contracts       = "yes"        # "-gnata"
style_checks    = "yes"        # "-gnaty3", "-gnatya", "-gnatyA", "-gnatyB", "-gnatyb", "-gnatyc", "-gnaty-d", "-gnatye", "-gnatyf", "-gnatyh", "-gnatyi", "-gnatyI", "-gnatyk", "-gnatyl", "-gnatym", "-gnatyn", "-gnatyO", "-gnatyp", "-gnatyr", "-gnatyS", "-gnatyt", "-gnatyu", "-gnatyx"

[build-switches.development]
optimization    = "debug"      # "-Os", "-gnatn", "-ffunction-sections", "-fdata-sections"
debug_info      = "yes"        # "-g"
runtime_checks  = "default"    #
compile_checks  = "warnings"   # "-gnatwa", "-gnatw.X", "-gnatVa"
contracts       = "yes"        # "-gnata"
style_checks    = "no"         #

[configuration.variables]
Buffer_Cache_Disable = {type = "Boolean", default = false}
Preread_Enable = {type = "Boolean", default = false}
Prefetch_Enable = {type = "Boolean", default = false}
Tick_Init_Priority = {type = "Integer", first = 0, last = 3, default = 3}
Disable_Restrictions = {type = "Boolean", default = false}
