name = "stm32l0xx_hal"
description = "HAL library for STMicroelectronics' STM32L0 MCU series"
version = "0.4.1-dev"

authors = ["Emanuele Zarfati"]
maintainers = ["Emanuele Zarfati <zarfati.tecno@gmail.com>"]
maintainers-logins = ["ezetec"]

[[depends-on]]
gnat_arm_elf = "^13.2.1"
stm32l0xx_cmsis = "1.0.0"

[[pins]]
stm32l0xx_cmsis = { url='https://gitlab.com/ezetec-alire-crates/stm32l0xx-cmsis.git', commit="7f6c3b2e5ea4dd9d2a688a5257fbb74bdafa2b7e"}

[build-switches]
"*".ada_version = ["-gnatX0"]

[configuration.variables]
Buffer_Cache_Disable = {type = "Boolean", default = false}
Preread_Enable = {type = "Boolean", default = false}
Prefetch_Enable = {type = "Boolean", default = false}
Tick_Init_Priority = {type = "Integer", first = 0, last = 3, default = 3}