name = "stm32l0xx_hal"
description = "HAL library for STMicroelectronics' STM32L0 MCU series"
version = "0.0.3-dev"

authors = ["Emanuele Zarfati"]
maintainers = ["Emanuele Zarfati <zarfati.tecno@gmail.com>"]
maintainers-logins = ["ezetec"]

[[depends-on]]
gnat_arm_elf = "^13.2.1"
stm32l0xx_cmsis = "0.1.0-dev"

[[pins]]
stm32l0xx_cmsis = { url='https://gitlab.com/ezetec-alire-crates/stm32l0xx-cmsis.git', commit="a047f37d2c8d78e1be5ff65f864d603cb5d34d3c"}

[build-switches]
"*".Ada_Version = "Ada2022"

[configuration.variables]
Buffer_Cache_Disable = {type = "Boolean", default = false}
Preread_Enable = {type = "Boolean", default = false}
Prefetch_Enable = {type = "Boolean", default = false}
Tick_Init_Priority = {type = "Integer", first = 0, last = 3, default = 3}