= Alire Crate - STM32L0xx HAL
Emanuele Zarfati <zarfati.tecno@gmail.com>
:toc:

This repository provides the
link:https://en.wikipedia.org/wiki/HAL_%28software%29[HAL] library for the
STMicroelectronics
link:https://www.st.com/en/microcontrollers-microprocessors/stm32l0-series.html[STM32L0]
MCU series and is intended to be distributed via the
link:https://alire.ada.dev/[Alire] package manager. This library, ported from
C to Ada, is based on the following projects:

.Credits
[cols="3,^1",width=75%,frame=none,grid=rows,role=center]
|===
| Project | Version

| STMicroelectronics's STM32CubeL0 HAL Driver MCU Component |
link:https://github.com/STMicroelectronics/stm32l0xx_hal_driver/tree/v1.10.6[v1.10.6]

|===


== License

Licensed under the link:http://www.apache.org/licenses/LICENSE-2.0[Apache
License, Version 2.0].

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations under
the License.


== Development

Requests and reporting::
Please report bugs or feature requests to the project maintainers, preferably
using the
link:https://gitlab.com/ezetec-alire-crates/stm32l0xx-hal/-/issues[issues
tracker].

Workflow:: The project development workflow is inspired by the
link:https://nvie.com/posts/a-successful-git-branching-model/[GitFlow]
branching model. Although strict naming conventions are not enforced,
`feature` branches should branch from `develop` and `fix` branches from `main`
or latest `release`.

Documentation:: The Specification (`.ads`) files are annotated to ease the
extract the documentation through AdaCore's
link:https://docs.adacore.com/live/wave/gnatdoc4/html/gnatdoc-doc/index.html[GNATdoc].
The tool is available as link:https://alire.ada.dev/crates/gnatdoc[Alire
crate]. Retrieve and compile GNATdoc it with:
+
.Retrieve GNATdoc
[source, console]
----
$ alr get --build gnatdoc
----
+
Append the resulting `gnatdoc_<...>/bin/` directory to `$PATH` and create the
following Alire alias:
+
.Create the alire alias for gnatdoc
[source, console]
----
$ alr config --set alias.doc "exec -P gnatdoc"
----
+
Finally, generate the HTML documentation executing `alr doc`.
